#!/usr/bin/env python3
"""Generate Report 2 Chapter 4's bounded CPU/GPU validation table."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SOURCE = ROOT / "experiments/week16/cpu_gpu_hardware_axis/summary.json"
DEFAULT_OUTPUT = (
    ROOT
    / "report2/phd-thesis-template-2.4/Chapter4/chapter4_cpu_gpu_table.tex"
)

CASE_LABELS = {
    "brio_wu_1d": ("Brio--Wu", "$800\\times1$"),
    "orszag_tang_2d": ("Orszag--Tang", "$256^2$"),
}
PRECISION_LABELS = {"double": "fp64", "float": "fp32"}


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    result.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    result.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return result


def validate_and_order(rows: list[dict]) -> list[dict]:
    keyed = {(row["case"], row["precision"]): row for row in rows}
    expected = [
        ("brio_wu_1d", "double"),
        ("brio_wu_1d", "float"),
        ("orszag_tang_2d", "double"),
        ("orszag_tang_2d", "float"),
    ]
    if set(keyed) != set(expected):
        raise ValueError(f"expected exactly four bounded rows, found {sorted(keyed)}")

    ordered = [keyed[key] for key in expected]
    for row in ordered:
        if row["steps_cpu"] != row["steps_gpu"]:
            raise ValueError(f"step mismatch for {row['case']} {row['precision']}")
        if row["ulp_max"] != 0 or row["linf_abs"] != 0:
            raise ValueError(f"non-zero saved-state difference for {row['case']}")
        if not row.get("gate_passed", False):
            raise ValueError(f"failed validation row for {row['case']}")
    return ordered


def render(rows: list[dict], source: Path) -> str:
    source_display = source.resolve().relative_to(ROOT).as_posix()
    body = []
    for row in rows:
        case, grid = CASE_LABELS[row["case"]]
        precision = PRECISION_LABELS[row["precision"]]
        steps = f"{row['steps_cpu']}/{row['steps_gpu']}"
        body.append(
            f"{case} & {precision} & {grid} & {steps} & 0 & 0 & "
            "HLL saved state \\\\"
        )

    return "\n".join(
        [
            "% Generated by scripts/figures/report2_chapter4_cpu_gpu_table.py",
            f"% Source: {source_display}",
            "\\begin{table}[htbp]",
            "\\centering",
            "\\small",
            "\\begin{tabularx}{\\textwidth}{@{}llccccX@{}}",
            "\\toprule",
            "Case & Precision & Grid & CPU/GPU steps & $\\mathrm{ULP}_{\\max}$ & "
            "$L_\\infty$ & Validated output \\\\",
            "\\midrule \\addlinespace[2pt]",
            *body,
            "\\bottomrule",
            "\\end{tabularx}",
            "\\caption[Matched CPU/GPU MHD validation]{\\textbf{Matched CPU/GPU "
            "MHD validation.} Same-precision CPU and GPU HLL runs used one matched "
            "case configuration on the local Intel Core Ultra 9 275HX/RTX 5070 "
            "Laptop GPU workstation. Steps are reported as CPU/GPU; $L_\\infty$ is the "
            "absolute saved-state difference. All four comparisons are bit-identical. "
            "The scope excludes HLLD, Kelvin--Helmholtz, GPU MCA, and other devices.}",
            "\\label{tab:ch4-cpu-gpu}",
            "\\end{table}",
            "",
        ]
    )


def main() -> int:
    args = parser().parse_args()
    source = args.source.resolve()
    payload = json.loads(source.read_text(encoding="utf-8"))
    rows = validate_and_order(payload["rows"])
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(rows, source), encoding="utf-8", newline="\n")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
